FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build && \
    npx prisma generate

EXPOSE 4000

CMD ["npm", "run", "start:dev-src"]