services:
  postgres:
    image: postgres:17
    build:
      context: .
      dockerfile: Dockerfile-postgres
    env_file: '.env'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/var/log/postgresql
    networks:
      - network
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - '${PORT}:4000'
    env_file:
      - '.env'
    environment:
      DATABASE_URL: '${DATABASE_URL}'
    depends_on:
      - postgres
    networks:
      - network
    restart: always

volumes:
  data:
  logs:

networks:
  network:
    driver: bridge
