FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY prisma ./prisma
COPY .env .env
COPY . .

RUN npm run build && \
    npx prisma generate && \
    npx prisma migrate dev --name init

EXPOSE 4000

CMD ["npm", "run",  "start:dev-src"]